#配置读取的环境
spring:
  profiles:
    active: dev
    # .50
    #active: pre
    # .176
    #active: test
    # .234
    #active: pro

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapper/*.xml
  #注意：对应实体类的路径
  type-aliases-package: com.enuos.live.pojo

pagehelper:
  helper-dialect: mysql
  #启用合理化，如果pageNum < 1 会查询第一页，如果 pageNum > pages 会查询最后一页
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

logging:
  level:
    com.enuos.live.mapper: DEBUG
  config: classpath:logback-spring.xml

