// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C10003Msg.proto

package com.enuos.live.proto.c10003msg;

public final class C10003 {
  private C10003() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C100030c2sOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 targetId = 1;
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    boolean hasTargetId();
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    long getTargetId();
  }
  /**
   * Protobuf type {@code Platform.ModelC10003.C100030c2s}
   *
   * <pre>
   * 添加申请
   * </pre>
   */
  public static final class C100030c2s extends
      com.google.protobuf.GeneratedMessage
      implements C100030c2sOrBuilder {
    // Use C100030c2s.newBuilder() to construct.
    private C100030c2s(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100030c2s(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100030c2s defaultInstance;
    public static C100030c2s getDefaultInstance() {
      return defaultInstance;
    }

    public C100030c2s getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100030c2s(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030c2s_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030c2s_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.c10003msg.C10003.C100030c2s.class, com.enuos.live.proto.c10003msg.C10003.C100030c2s.Builder.class);
    }

    public static com.google.protobuf.Parser<C100030c2s> PARSER =
        new com.google.protobuf.AbstractParser<C100030c2s>() {
      public C100030c2s parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100030c2s(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100030c2s> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 targetId = 1;
    public static final int TARGETID_FIELD_NUMBER = 1;
    private long targetId_;
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    public long getTargetId() {
      return targetId_;
    }

    private void initFields() {
      targetId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTargetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030c2s parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.c10003msg.C10003.C100030c2s prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10003.C100030c2s}
     *
     * <pre>
     * 添加申请
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.c10003msg.C10003.C100030c2sOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030c2s_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030c2s_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.c10003msg.C10003.C100030c2s.class, com.enuos.live.proto.c10003msg.C10003.C100030c2s.Builder.class);
      }

      // Construct using com.enuos.live.proto.c10003msg.C10003.C100030c2s.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030c2s_descriptor;
      }

      public com.enuos.live.proto.c10003msg.C10003.C100030c2s getDefaultInstanceForType() {
        return com.enuos.live.proto.c10003msg.C10003.C100030c2s.getDefaultInstance();
      }

      public com.enuos.live.proto.c10003msg.C10003.C100030c2s build() {
        com.enuos.live.proto.c10003msg.C10003.C100030c2s result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.c10003msg.C10003.C100030c2s buildPartial() {
        com.enuos.live.proto.c10003msg.C10003.C100030c2s result = new com.enuos.live.proto.c10003msg.C10003.C100030c2s(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetId_ = targetId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.c10003msg.C10003.C100030c2s) {
          return mergeFrom((com.enuos.live.proto.c10003msg.C10003.C100030c2s)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.c10003msg.C10003.C100030c2s other) {
        if (other == com.enuos.live.proto.c10003msg.C10003.C100030c2s.getDefaultInstance()) return this;
        if (other.hasTargetId()) {
          setTargetId(other.getTargetId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTargetId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.c10003msg.C10003.C100030c2s parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.c10003msg.C10003.C100030c2s) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 targetId = 1;
      private long targetId_ ;
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public Builder setTargetId(long value) {
        bitField0_ |= 0x00000001;
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10003.C100030c2s)
    }

    static {
      defaultInstance = new C100030c2s(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10003.C100030c2s)
  }

  public interface C100030s2cOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 targetId = 1;
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    boolean hasTargetId();
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    long getTargetId();

    // required int32 result = 2;
    /**
     * <code>required int32 result = 2;</code>
     *
     * <pre>
     * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 2;</code>
     *
     * <pre>
     * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
     * </pre>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code Platform.ModelC10003.C100030s2c}
   */
  public static final class C100030s2c extends
      com.google.protobuf.GeneratedMessage
      implements C100030s2cOrBuilder {
    // Use C100030s2c.newBuilder() to construct.
    private C100030s2c(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100030s2c(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100030s2c defaultInstance;
    public static C100030s2c getDefaultInstance() {
      return defaultInstance;
    }

    public C100030s2c getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100030s2c(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030s2c_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030s2c_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.c10003msg.C10003.C100030s2c.class, com.enuos.live.proto.c10003msg.C10003.C100030s2c.Builder.class);
    }

    public static com.google.protobuf.Parser<C100030s2c> PARSER =
        new com.google.protobuf.AbstractParser<C100030s2c>() {
      public C100030s2c parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100030s2c(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100030s2c> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 targetId = 1;
    public static final int TARGETID_FIELD_NUMBER = 1;
    private long targetId_;
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 targetId = 1;</code>
     *
     * <pre>
     * 目标id 【添加目标用户id】
     * </pre>
     */
    public long getTargetId() {
      return targetId_;
    }

    // required int32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>required int32 result = 2;</code>
     *
     * <pre>
     * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 result = 2;</code>
     *
     * <pre>
     * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      targetId_ = 0L;
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTargetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10003msg.C10003.C100030s2c parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.c10003msg.C10003.C100030s2c prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10003.C100030s2c}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.c10003msg.C10003.C100030s2cOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030s2c_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030s2c_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.c10003msg.C10003.C100030s2c.class, com.enuos.live.proto.c10003msg.C10003.C100030s2c.Builder.class);
      }

      // Construct using com.enuos.live.proto.c10003msg.C10003.C100030s2c.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.c10003msg.C10003.internal_static_Platform_ModelC10003_C100030s2c_descriptor;
      }

      public com.enuos.live.proto.c10003msg.C10003.C100030s2c getDefaultInstanceForType() {
        return com.enuos.live.proto.c10003msg.C10003.C100030s2c.getDefaultInstance();
      }

      public com.enuos.live.proto.c10003msg.C10003.C100030s2c build() {
        com.enuos.live.proto.c10003msg.C10003.C100030s2c result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.c10003msg.C10003.C100030s2c buildPartial() {
        com.enuos.live.proto.c10003msg.C10003.C100030s2c result = new com.enuos.live.proto.c10003msg.C10003.C100030s2c(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetId_ = targetId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.c10003msg.C10003.C100030s2c) {
          return mergeFrom((com.enuos.live.proto.c10003msg.C10003.C100030s2c)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.c10003msg.C10003.C100030s2c other) {
        if (other == com.enuos.live.proto.c10003msg.C10003.C100030s2c.getDefaultInstance()) return this;
        if (other.hasTargetId()) {
          setTargetId(other.getTargetId());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTargetId()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.c10003msg.C10003.C100030s2c parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.c10003msg.C10003.C100030s2c) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 targetId = 1;
      private long targetId_ ;
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public Builder setTargetId(long value) {
        bitField0_ |= 0x00000001;
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 targetId = 1;</code>
       *
       * <pre>
       * 目标id 【添加目标用户id】
       * </pre>
       */
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 result = 2;
      private int result_ ;
      /**
       * <code>required int32 result = 2;</code>
       *
       * <pre>
       * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 result = 2;</code>
       *
       * <pre>
       * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 2;</code>
       *
       * <pre>
       * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 2;</code>
       *
       * <pre>
       * 返回结果 【0 发送成功 1 发送失败 2 重复发送添加请求 3 添加好友】
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10003.C100030s2c)
    }

    static {
      defaultInstance = new C100030s2c(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10003.C100030s2c)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10003_C100030c2s_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10003_C100030c2s_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10003_C100030s2c_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10003_C100030s2c_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017C10003Msg.proto\022\024Platform.ModelC10003\"" +
      "\036\n\nC100030c2s\022\020\n\010targetId\030\001 \002(\003\".\n\nC1000" +
      "30s2c\022\020\n\010targetId\030\001 \002(\003\022\016\n\006result\030\002 \002(\005B" +
      "(\n\036com.enuos.live.proto.c10003msgB\006C1000" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_ModelC10003_C100030c2s_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_ModelC10003_C100030c2s_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10003_C100030c2s_descriptor,
              new java.lang.String[] { "TargetId", });
          internal_static_Platform_ModelC10003_C100030s2c_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_ModelC10003_C100030s2c_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10003_C100030s2c_descriptor,
              new java.lang.String[] { "TargetId", "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
