// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: I10001Msg.proto

package com.enuos.live.proto.i10001msg;

public final class I10001 {
  private I10001() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 userId = 1;
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *玩家ID 
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *玩家ID 
     * </pre>
     */
    long getUserId();

    // required string iconUrl = 2;
    /**
     * <code>required string iconUrl = 2;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    boolean hasIconUrl();
    /**
     * <code>required string iconUrl = 2;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    java.lang.String getIconUrl();
    /**
     * <code>required string iconUrl = 2;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getIconUrlBytes();

    // required string nickName = 3;
    /**
     * <code>required string nickName = 3;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    boolean hasNickName();
    /**
     * <code>required string nickName = 3;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    java.lang.String getNickName();
    /**
     * <code>required string nickName = 3;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    // required int32 sex = 4;
    /**
     * <code>required int32 sex = 4;</code>
     *
     * <pre>
     *用户性别
     * </pre>
     */
    boolean hasSex();
    /**
     * <code>required int32 sex = 4;</code>
     *
     * <pre>
     *用户性别
     * </pre>
     */
    int getSex();

    // required int32 level = 5;
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    int getLevel();
  }
  /**
   * Protobuf type {@code Platform.ModelI10001.PlayerInfo}
   *
   * <pre>
   * 玩家信息
   * </pre>
   */
  public static final class PlayerInfo extends
      com.google.protobuf.GeneratedMessage
      implements PlayerInfoOrBuilder {
    // Use PlayerInfo.newBuilder() to construct.
    private PlayerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerInfo defaultInstance;
    public static PlayerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              iconUrl_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              nickName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sex_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_PlayerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.i10001msg.I10001.PlayerInfo.class, com.enuos.live.proto.i10001msg.I10001.PlayerInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerInfo> PARSER =
        new com.google.protobuf.AbstractParser<PlayerInfo>() {
      public PlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *玩家ID 
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *玩家ID 
     * </pre>
     */
    public long getUserId() {
      return userId_;
    }

    // required string iconUrl = 2;
    public static final int ICONURL_FIELD_NUMBER = 2;
    private java.lang.Object iconUrl_;
    /**
     * <code>required string iconUrl = 2;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    public boolean hasIconUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string iconUrl = 2;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    public java.lang.String getIconUrl() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          iconUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string iconUrl = 2;</code>
     *
     * <pre>
     *用户头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIconUrlBytes() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string nickName = 3;
    public static final int NICKNAME_FIELD_NUMBER = 3;
    private java.lang.Object nickName_;
    /**
     * <code>required string nickName = 3;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string nickName = 3;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nickName = 3;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 sex = 4;
    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>required int32 sex = 4;</code>
     *
     * <pre>
     *用户性别
     * </pre>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 sex = 4;</code>
     *
     * <pre>
     *用户性别
     * </pre>
     */
    public int getSex() {
      return sex_;
    }

    // required int32 level = 5;
    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *用户等级
     * </pre>
     */
    public int getLevel() {
      return level_;
    }

    private void initFields() {
      userId_ = 0L;
      iconUrl_ = "";
      nickName_ = "";
      sex_ = 0;
      level_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIconUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIconUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIconUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.i10001msg.I10001.PlayerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelI10001.PlayerInfo}
     *
     * <pre>
     * 玩家信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.i10001msg.I10001.PlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_PlayerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_PlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.i10001msg.I10001.PlayerInfo.class, com.enuos.live.proto.i10001msg.I10001.PlayerInfo.Builder.class);
      }

      // Construct using com.enuos.live.proto.i10001msg.I10001.PlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        iconUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_PlayerInfo_descriptor;
      }

      public com.enuos.live.proto.i10001msg.I10001.PlayerInfo getDefaultInstanceForType() {
        return com.enuos.live.proto.i10001msg.I10001.PlayerInfo.getDefaultInstance();
      }

      public com.enuos.live.proto.i10001msg.I10001.PlayerInfo build() {
        com.enuos.live.proto.i10001msg.I10001.PlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.i10001msg.I10001.PlayerInfo buildPartial() {
        com.enuos.live.proto.i10001msg.I10001.PlayerInfo result = new com.enuos.live.proto.i10001msg.I10001.PlayerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.iconUrl_ = iconUrl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.i10001msg.I10001.PlayerInfo) {
          return mergeFrom((com.enuos.live.proto.i10001msg.I10001.PlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.i10001msg.I10001.PlayerInfo other) {
        if (other == com.enuos.live.proto.i10001msg.I10001.PlayerInfo.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasIconUrl()) {
          bitField0_ |= 0x00000002;
          iconUrl_ = other.iconUrl_;
          onChanged();
        }
        if (other.hasNickName()) {
          bitField0_ |= 0x00000004;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasIconUrl()) {
          
          return false;
        }
        if (!hasNickName()) {
          
          return false;
        }
        if (!hasSex()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.i10001msg.I10001.PlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.i10001msg.I10001.PlayerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 userId = 1;
      private long userId_ ;
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *玩家ID 
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *玩家ID 
       * </pre>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *玩家ID 
       * </pre>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *玩家ID 
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required string iconUrl = 2;
      private java.lang.Object iconUrl_ = "";
      /**
       * <code>required string iconUrl = 2;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public boolean hasIconUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string iconUrl = 2;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public java.lang.String getIconUrl() {
        java.lang.Object ref = iconUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          iconUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string iconUrl = 2;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIconUrlBytes() {
        java.lang.Object ref = iconUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string iconUrl = 2;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public Builder setIconUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        iconUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string iconUrl = 2;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public Builder clearIconUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iconUrl_ = getDefaultInstance().getIconUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string iconUrl = 2;</code>
       *
       * <pre>
       *用户头像
       * </pre>
       */
      public Builder setIconUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        iconUrl_ = value;
        onChanged();
        return this;
      }

      // required string nickName = 3;
      private java.lang.Object nickName_ = "";
      /**
       * <code>required string nickName = 3;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string nickName = 3;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nickName = 3;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nickName = 3;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nickName = 3;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>required string nickName = 3;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickName_ = value;
        onChanged();
        return this;
      }

      // required int32 sex = 4;
      private int sex_ ;
      /**
       * <code>required int32 sex = 4;</code>
       *
       * <pre>
       *用户性别
       * </pre>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 sex = 4;</code>
       *
       * <pre>
       *用户性别
       * </pre>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>required int32 sex = 4;</code>
       *
       * <pre>
       *用户性别
       * </pre>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sex = 4;</code>
       *
       * <pre>
       *用户性别
       * </pre>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        onChanged();
        return this;
      }

      // required int32 level = 5;
      private int level_ ;
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *用户等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelI10001.PlayerInfo)
    }

    static {
      defaultInstance = new PlayerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelI10001.PlayerInfo)
  }

  public interface JoinGameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 gameId = 1;
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    boolean hasGameId();
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    long getGameId();

    // required int64 roomId = 2;
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID 
     * </pre>
     */
    boolean hasRoomId();
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID 
     * </pre>
     */
    long getRoomId();
  }
  /**
   * Protobuf type {@code Platform.ModelI10001.JoinGame}
   *
   * <pre>
   * 加入游戏
   * </pre>
   */
  public static final class JoinGame extends
      com.google.protobuf.GeneratedMessage
      implements JoinGameOrBuilder {
    // Use JoinGame.newBuilder() to construct.
    private JoinGame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinGame(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinGame defaultInstance;
    public static JoinGame getDefaultInstance() {
      return defaultInstance;
    }

    public JoinGame getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinGame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gameId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roomId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_JoinGame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_JoinGame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.i10001msg.I10001.JoinGame.class, com.enuos.live.proto.i10001msg.I10001.JoinGame.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinGame> PARSER =
        new com.google.protobuf.AbstractParser<JoinGame>() {
      public JoinGame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinGame(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinGame> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 gameId = 1;
    public static final int GAMEID_FIELD_NUMBER = 1;
    private long gameId_;
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    public long getGameId() {
      return gameId_;
    }

    // required int64 roomId = 2;
    public static final int ROOMID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID 
     * </pre>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID 
     * </pre>
     */
    public long getRoomId() {
      return roomId_;
    }

    private void initFields() {
      gameId_ = 0L;
      roomId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGameId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gameId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, roomId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gameId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, roomId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.JoinGame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.i10001msg.I10001.JoinGame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelI10001.JoinGame}
     *
     * <pre>
     * 加入游戏
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.i10001msg.I10001.JoinGameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_JoinGame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_JoinGame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.i10001msg.I10001.JoinGame.class, com.enuos.live.proto.i10001msg.I10001.JoinGame.Builder.class);
      }

      // Construct using com.enuos.live.proto.i10001msg.I10001.JoinGame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gameId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_JoinGame_descriptor;
      }

      public com.enuos.live.proto.i10001msg.I10001.JoinGame getDefaultInstanceForType() {
        return com.enuos.live.proto.i10001msg.I10001.JoinGame.getDefaultInstance();
      }

      public com.enuos.live.proto.i10001msg.I10001.JoinGame build() {
        com.enuos.live.proto.i10001msg.I10001.JoinGame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.i10001msg.I10001.JoinGame buildPartial() {
        com.enuos.live.proto.i10001msg.I10001.JoinGame result = new com.enuos.live.proto.i10001msg.I10001.JoinGame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameId_ = gameId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomId_ = roomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.i10001msg.I10001.JoinGame) {
          return mergeFrom((com.enuos.live.proto.i10001msg.I10001.JoinGame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.i10001msg.I10001.JoinGame other) {
        if (other == com.enuos.live.proto.i10001msg.I10001.JoinGame.getDefaultInstance()) return this;
        if (other.hasGameId()) {
          setGameId(other.getGameId());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGameId()) {
          
          return false;
        }
        if (!hasRoomId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.i10001msg.I10001.JoinGame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.i10001msg.I10001.JoinGame) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 gameId = 1;
      private long gameId_ ;
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public long getGameId() {
        return gameId_;
      }
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public Builder setGameId(long value) {
        bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 roomId = 2;
      private long roomId_ ;
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID 
       * </pre>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID 
       * </pre>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID 
       * </pre>
       */
      public Builder setRoomId(long value) {
        bitField0_ |= 0x00000002;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID 
       * </pre>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelI10001.JoinGame)
    }

    static {
      defaultInstance = new JoinGame(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelI10001.JoinGame)
  }

  public interface RoomRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 gameId = 1;
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    boolean hasGameId();
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    long getGameId();

    // required int64 roomId = 2;
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID
     * </pre>
     */
    boolean hasRoomId();
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID
     * </pre>
     */
    long getRoomId();

    // optional int32 openWay = 3;
    /**
     * <code>optional int32 openWay = 3;</code>
     *
     * <pre>
     *开放方式
     * </pre>
     */
    boolean hasOpenWay();
    /**
     * <code>optional int32 openWay = 3;</code>
     *
     * <pre>
     *开放方式
     * </pre>
     */
    int getOpenWay();

    // optional int32 roomType = 4;
    /**
     * <code>optional int32 roomType = 4;</code>
     *
     * <pre>
     * 0-公开 1-创建
     * </pre>
     */
    boolean hasRoomType();
    /**
     * <code>optional int32 roomType = 4;</code>
     *
     * <pre>
     * 0-公开 1-创建
     * </pre>
     */
    int getRoomType();

    // optional int32 gameMode = 5;
    /**
     * <code>optional int32 gameMode = 5;</code>
     *
     * <pre>
     * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
     * </pre>
     */
    boolean hasGameMode();
    /**
     * <code>optional int32 gameMode = 5;</code>
     *
     * <pre>
     * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
     * </pre>
     */
    int getGameMode();

    // optional int32 speakMode = 6;
    /**
     * <code>optional int32 speakMode = 6;</code>
     *
     * <pre>
     * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
     * 0-经典 1-癞子 ==&gt; 7乐斗地主
     * </pre>
     */
    boolean hasSpeakMode();
    /**
     * <code>optional int32 speakMode = 6;</code>
     *
     * <pre>
     * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
     * 0-经典 1-癞子 ==&gt; 7乐斗地主
     * </pre>
     */
    int getSpeakMode();

    // optional int32 gameNumber = 7;
    /**
     * <code>optional int32 gameNumber = 7;</code>
     *
     * <pre>
     * 0-文字 1-语音 ==&gt; 谁是卧底
     * </pre>
     */
    boolean hasGameNumber();
    /**
     * <code>optional int32 gameNumber = 7;</code>
     *
     * <pre>
     * 0-文字 1-语音 ==&gt; 谁是卧底
     * </pre>
     */
    int getGameNumber();

    // optional int32 gameSession = 8;
    /**
     * <code>optional int32 gameSession = 8;</code>
     *
     * <pre>
     * 0-[2人] 1-[4人] ==&gt; 飞行棋
     * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
     * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
     * </pre>
     */
    boolean hasGameSession();
    /**
     * <code>optional int32 gameSession = 8;</code>
     *
     * <pre>
     * 0-[2人] 1-[4人] ==&gt; 飞行棋
     * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
     * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
     * </pre>
     */
    int getGameSession();
  }
  /**
   * Protobuf type {@code Platform.ModelI10001.RoomRecord}
   *
   * <pre>
   * 房间记录
   * </pre>
   */
  public static final class RoomRecord extends
      com.google.protobuf.GeneratedMessage
      implements RoomRecordOrBuilder {
    // Use RoomRecord.newBuilder() to construct.
    private RoomRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoomRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoomRecord defaultInstance;
    public static RoomRecord getDefaultInstance() {
      return defaultInstance;
    }

    public RoomRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoomRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gameId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roomId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              openWay_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              roomType_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gameMode_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              speakMode_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              gameNumber_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              gameSession_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_RoomRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_RoomRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.i10001msg.I10001.RoomRecord.class, com.enuos.live.proto.i10001msg.I10001.RoomRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<RoomRecord> PARSER =
        new com.google.protobuf.AbstractParser<RoomRecord>() {
      public RoomRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoomRecord> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 gameId = 1;
    public static final int GAMEID_FIELD_NUMBER = 1;
    private long gameId_;
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 gameId = 1;</code>
     *
     * <pre>
     *游戏ID
     * </pre>
     */
    public long getGameId() {
      return gameId_;
    }

    // required int64 roomId = 2;
    public static final int ROOMID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID
     * </pre>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 roomId = 2;</code>
     *
     * <pre>
     *房间ID
     * </pre>
     */
    public long getRoomId() {
      return roomId_;
    }

    // optional int32 openWay = 3;
    public static final int OPENWAY_FIELD_NUMBER = 3;
    private int openWay_;
    /**
     * <code>optional int32 openWay = 3;</code>
     *
     * <pre>
     *开放方式
     * </pre>
     */
    public boolean hasOpenWay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 openWay = 3;</code>
     *
     * <pre>
     *开放方式
     * </pre>
     */
    public int getOpenWay() {
      return openWay_;
    }

    // optional int32 roomType = 4;
    public static final int ROOMTYPE_FIELD_NUMBER = 4;
    private int roomType_;
    /**
     * <code>optional int32 roomType = 4;</code>
     *
     * <pre>
     * 0-公开 1-创建
     * </pre>
     */
    public boolean hasRoomType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 roomType = 4;</code>
     *
     * <pre>
     * 0-公开 1-创建
     * </pre>
     */
    public int getRoomType() {
      return roomType_;
    }

    // optional int32 gameMode = 5;
    public static final int GAMEMODE_FIELD_NUMBER = 5;
    private int gameMode_;
    /**
     * <code>optional int32 gameMode = 5;</code>
     *
     * <pre>
     * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
     * </pre>
     */
    public boolean hasGameMode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 gameMode = 5;</code>
     *
     * <pre>
     * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
     * </pre>
     */
    public int getGameMode() {
      return gameMode_;
    }

    // optional int32 speakMode = 6;
    public static final int SPEAKMODE_FIELD_NUMBER = 6;
    private int speakMode_;
    /**
     * <code>optional int32 speakMode = 6;</code>
     *
     * <pre>
     * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
     * 0-经典 1-癞子 ==&gt; 7乐斗地主
     * </pre>
     */
    public boolean hasSpeakMode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 speakMode = 6;</code>
     *
     * <pre>
     * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
     * 0-经典 1-癞子 ==&gt; 7乐斗地主
     * </pre>
     */
    public int getSpeakMode() {
      return speakMode_;
    }

    // optional int32 gameNumber = 7;
    public static final int GAMENUMBER_FIELD_NUMBER = 7;
    private int gameNumber_;
    /**
     * <code>optional int32 gameNumber = 7;</code>
     *
     * <pre>
     * 0-文字 1-语音 ==&gt; 谁是卧底
     * </pre>
     */
    public boolean hasGameNumber() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 gameNumber = 7;</code>
     *
     * <pre>
     * 0-文字 1-语音 ==&gt; 谁是卧底
     * </pre>
     */
    public int getGameNumber() {
      return gameNumber_;
    }

    // optional int32 gameSession = 8;
    public static final int GAMESESSION_FIELD_NUMBER = 8;
    private int gameSession_;
    /**
     * <code>optional int32 gameSession = 8;</code>
     *
     * <pre>
     * 0-[2人] 1-[4人] ==&gt; 飞行棋
     * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
     * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
     * </pre>
     */
    public boolean hasGameSession() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 gameSession = 8;</code>
     *
     * <pre>
     * 0-[2人] 1-[4人] ==&gt; 飞行棋
     * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
     * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
     * </pre>
     */
    public int getGameSession() {
      return gameSession_;
    }

    private void initFields() {
      gameId_ = 0L;
      roomId_ = 0L;
      openWay_ = 0;
      roomType_ = 0;
      gameMode_ = 0;
      speakMode_ = 0;
      gameNumber_ = 0;
      gameSession_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGameId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gameId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, roomId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, openWay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, roomType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, gameMode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, speakMode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, gameNumber_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, gameSession_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gameId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, roomId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, openWay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, roomType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, gameMode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, speakMode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, gameNumber_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, gameSession_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.i10001msg.I10001.RoomRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.i10001msg.I10001.RoomRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelI10001.RoomRecord}
     *
     * <pre>
     * 房间记录
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.i10001msg.I10001.RoomRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_RoomRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_RoomRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.i10001msg.I10001.RoomRecord.class, com.enuos.live.proto.i10001msg.I10001.RoomRecord.Builder.class);
      }

      // Construct using com.enuos.live.proto.i10001msg.I10001.RoomRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gameId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        openWay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        roomType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gameMode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        speakMode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        gameNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        gameSession_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.i10001msg.I10001.internal_static_Platform_ModelI10001_RoomRecord_descriptor;
      }

      public com.enuos.live.proto.i10001msg.I10001.RoomRecord getDefaultInstanceForType() {
        return com.enuos.live.proto.i10001msg.I10001.RoomRecord.getDefaultInstance();
      }

      public com.enuos.live.proto.i10001msg.I10001.RoomRecord build() {
        com.enuos.live.proto.i10001msg.I10001.RoomRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.i10001msg.I10001.RoomRecord buildPartial() {
        com.enuos.live.proto.i10001msg.I10001.RoomRecord result = new com.enuos.live.proto.i10001msg.I10001.RoomRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameId_ = gameId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomId_ = roomId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.openWay_ = openWay_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.roomType_ = roomType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gameMode_ = gameMode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.speakMode_ = speakMode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gameNumber_ = gameNumber_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.gameSession_ = gameSession_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.i10001msg.I10001.RoomRecord) {
          return mergeFrom((com.enuos.live.proto.i10001msg.I10001.RoomRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.i10001msg.I10001.RoomRecord other) {
        if (other == com.enuos.live.proto.i10001msg.I10001.RoomRecord.getDefaultInstance()) return this;
        if (other.hasGameId()) {
          setGameId(other.getGameId());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasOpenWay()) {
          setOpenWay(other.getOpenWay());
        }
        if (other.hasRoomType()) {
          setRoomType(other.getRoomType());
        }
        if (other.hasGameMode()) {
          setGameMode(other.getGameMode());
        }
        if (other.hasSpeakMode()) {
          setSpeakMode(other.getSpeakMode());
        }
        if (other.hasGameNumber()) {
          setGameNumber(other.getGameNumber());
        }
        if (other.hasGameSession()) {
          setGameSession(other.getGameSession());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGameId()) {
          
          return false;
        }
        if (!hasRoomId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.i10001msg.I10001.RoomRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.i10001msg.I10001.RoomRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 gameId = 1;
      private long gameId_ ;
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public long getGameId() {
        return gameId_;
      }
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public Builder setGameId(long value) {
        bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 gameId = 1;</code>
       *
       * <pre>
       *游戏ID
       * </pre>
       */
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 roomId = 2;
      private long roomId_ ;
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID
       * </pre>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID
       * </pre>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID
       * </pre>
       */
      public Builder setRoomId(long value) {
        bitField0_ |= 0x00000002;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roomId = 2;</code>
       *
       * <pre>
       *房间ID
       * </pre>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 openWay = 3;
      private int openWay_ ;
      /**
       * <code>optional int32 openWay = 3;</code>
       *
       * <pre>
       *开放方式
       * </pre>
       */
      public boolean hasOpenWay() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 openWay = 3;</code>
       *
       * <pre>
       *开放方式
       * </pre>
       */
      public int getOpenWay() {
        return openWay_;
      }
      /**
       * <code>optional int32 openWay = 3;</code>
       *
       * <pre>
       *开放方式
       * </pre>
       */
      public Builder setOpenWay(int value) {
        bitField0_ |= 0x00000004;
        openWay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 openWay = 3;</code>
       *
       * <pre>
       *开放方式
       * </pre>
       */
      public Builder clearOpenWay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        openWay_ = 0;
        onChanged();
        return this;
      }

      // optional int32 roomType = 4;
      private int roomType_ ;
      /**
       * <code>optional int32 roomType = 4;</code>
       *
       * <pre>
       * 0-公开 1-创建
       * </pre>
       */
      public boolean hasRoomType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 roomType = 4;</code>
       *
       * <pre>
       * 0-公开 1-创建
       * </pre>
       */
      public int getRoomType() {
        return roomType_;
      }
      /**
       * <code>optional int32 roomType = 4;</code>
       *
       * <pre>
       * 0-公开 1-创建
       * </pre>
       */
      public Builder setRoomType(int value) {
        bitField0_ |= 0x00000008;
        roomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roomType = 4;</code>
       *
       * <pre>
       * 0-公开 1-创建
       * </pre>
       */
      public Builder clearRoomType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        roomType_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gameMode = 5;
      private int gameMode_ ;
      /**
       * <code>optional int32 gameMode = 5;</code>
       *
       * <pre>
       * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
       * </pre>
       */
      public boolean hasGameMode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 gameMode = 5;</code>
       *
       * <pre>
       * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
       * </pre>
       */
      public int getGameMode() {
        return gameMode_;
      }
      /**
       * <code>optional int32 gameMode = 5;</code>
       *
       * <pre>
       * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
       * </pre>
       */
      public Builder setGameMode(int value) {
        bitField0_ |= 0x00000010;
        gameMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gameMode = 5;</code>
       *
       * <pre>
       * 0-[1卧底] 1-[2卧底] ==&gt; 谁是卧底
       * </pre>
       */
      public Builder clearGameMode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gameMode_ = 0;
        onChanged();
        return this;
      }

      // optional int32 speakMode = 6;
      private int speakMode_ ;
      /**
       * <code>optional int32 speakMode = 6;</code>
       *
       * <pre>
       * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
       * 0-经典 1-癞子 ==&gt; 7乐斗地主
       * </pre>
       */
      public boolean hasSpeakMode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 speakMode = 6;</code>
       *
       * <pre>
       * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
       * 0-经典 1-癞子 ==&gt; 7乐斗地主
       * </pre>
       */
      public int getSpeakMode() {
        return speakMode_;
      }
      /**
       * <code>optional int32 speakMode = 6;</code>
       *
       * <pre>
       * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
       * 0-经典 1-癞子 ==&gt; 7乐斗地主
       * </pre>
       */
      public Builder setSpeakMode(int value) {
        bitField0_ |= 0x00000020;
        speakMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 speakMode = 6;</code>
       *
       * <pre>
       * 0-血战到底 1-血流到底 ==&gt; 7乐麻将
       * 0-经典 1-癞子 ==&gt; 7乐斗地主
       * </pre>
       */
      public Builder clearSpeakMode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        speakMode_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gameNumber = 7;
      private int gameNumber_ ;
      /**
       * <code>optional int32 gameNumber = 7;</code>
       *
       * <pre>
       * 0-文字 1-语音 ==&gt; 谁是卧底
       * </pre>
       */
      public boolean hasGameNumber() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 gameNumber = 7;</code>
       *
       * <pre>
       * 0-文字 1-语音 ==&gt; 谁是卧底
       * </pre>
       */
      public int getGameNumber() {
        return gameNumber_;
      }
      /**
       * <code>optional int32 gameNumber = 7;</code>
       *
       * <pre>
       * 0-文字 1-语音 ==&gt; 谁是卧底
       * </pre>
       */
      public Builder setGameNumber(int value) {
        bitField0_ |= 0x00000040;
        gameNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gameNumber = 7;</code>
       *
       * <pre>
       * 0-文字 1-语音 ==&gt; 谁是卧底
       * </pre>
       */
      public Builder clearGameNumber() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gameNumber_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gameSession = 8;
      private int gameSession_ ;
      /**
       * <code>optional int32 gameSession = 8;</code>
       *
       * <pre>
       * 0-[2人] 1-[4人] ==&gt; 飞行棋
       * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
       * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
       * </pre>
       */
      public boolean hasGameSession() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 gameSession = 8;</code>
       *
       * <pre>
       * 0-[2人] 1-[4人] ==&gt; 飞行棋
       * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
       * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
       * </pre>
       */
      public int getGameSession() {
        return gameSession_;
      }
      /**
       * <code>optional int32 gameSession = 8;</code>
       *
       * <pre>
       * 0-[2人] 1-[4人] ==&gt; 飞行棋
       * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
       * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
       * </pre>
       */
      public Builder setGameSession(int value) {
        bitField0_ |= 0x00000080;
        gameSession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gameSession = 8;</code>
       *
       * <pre>
       * 0-[2人] 1-[4人] ==&gt; 飞行棋
       * 0-[4-6人] 1-[7-8人] ==&gt; 谁是卧底
       * 0-[6人] 1-[9人] 2-[12人] ==&gt; 狼人杀
       * </pre>
       */
      public Builder clearGameSession() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gameSession_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelI10001.RoomRecord)
    }

    static {
      defaultInstance = new RoomRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelI10001.RoomRecord)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelI10001_PlayerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelI10001_PlayerInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelI10001_JoinGame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelI10001_JoinGame_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelI10001_RoomRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelI10001_RoomRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017I10001Msg.proto\022\024Platform.ModelI10001\"" +
      "[\n\nPlayerInfo\022\016\n\006userId\030\001 \002(\003\022\017\n\007iconUrl" +
      "\030\002 \002(\t\022\020\n\010nickName\030\003 \002(\t\022\013\n\003sex\030\004 \002(\005\022\r\n" +
      "\005level\030\005 \002(\005\"*\n\010JoinGame\022\016\n\006gameId\030\001 \002(\003" +
      "\022\016\n\006roomId\030\002 \002(\003\"\235\001\n\nRoomRecord\022\016\n\006gameI" +
      "d\030\001 \002(\003\022\016\n\006roomId\030\002 \002(\003\022\017\n\007openWay\030\003 \001(\005" +
      "\022\020\n\010roomType\030\004 \001(\005\022\020\n\010gameMode\030\005 \001(\005\022\021\n\t" +
      "speakMode\030\006 \001(\005\022\022\n\ngameNumber\030\007 \001(\005\022\023\n\013g" +
      "ameSession\030\010 \001(\005B(\n\036com.enuos.live.proto" +
      ".i10001msgB\006I10001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_ModelI10001_PlayerInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_ModelI10001_PlayerInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelI10001_PlayerInfo_descriptor,
              new java.lang.String[] { "UserId", "IconUrl", "NickName", "Sex", "Level", });
          internal_static_Platform_ModelI10001_JoinGame_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_ModelI10001_JoinGame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelI10001_JoinGame_descriptor,
              new java.lang.String[] { "GameId", "RoomId", });
          internal_static_Platform_ModelI10001_RoomRecord_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Platform_ModelI10001_RoomRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelI10001_RoomRecord_descriptor,
              new java.lang.String[] { "GameId", "RoomId", "OpenWay", "RoomType", "GameMode", "SpeakMode", "GameNumber", "GameSession", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
