#server
server:
  port: 7020
  undertow:
    #是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    #设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    #不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 16
    #阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    #它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 256
    #以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    #每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024

#spring
spring:
  application:
    name: SOCKET-SERVER
  security:
    user:
      name: nanjing7le
      password: enuos2020
  #链路追踪
  zipkin:
    base-url: http://localhost:9771
    sender:
      type: web
  sleuth:
    sampler:
      #100%采样
      probability: 1.0
  #nacos注册中心
  cloud:
    nacos:
      discovery:
        #注册地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #dashboard
        dashboard: localhost:8088
        port: 8719
  #配置文件上传器
  servlet:
    multipart:
      enabled: true
      #单个文件的大小
      max-file-size: 100MB
      #单次请求的文件的总大小
      max-request-size: 100MB
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 20000
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10

#feign
feign:
  sentinel:
    #流量监控
    enabled: true
  httpclient:
    #是否启用httpclient
    enabled: false
    #请求连接超时时间（毫秒）
    connection-timeout: 3000
  okhttp:
    #是否启用http-ok（性能比httpclient高）
    enabled: true
#  hystrix:
#    #是否启用hystrix
#    enabled: true

#upload
upload:
  url: http://localhost:7100

# 设置房主离开房间超时时间: 单位秒
room:
  expTime: 1500
  # 设置语音房聊天文件最大值:单位MB
  fileSize: 10
  # 语音房发送消息最大字符长度
  messageSize: 100
#参数加解密
data:
  is-cipher: false