#配置读取的环境
spring:
  profiles:
    active: pro

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapper/*.xml
  #注意：对应实体类的路径
  type-aliases-package: com.enuos.live.pojo
  #对应实体属性自动转为驼峰命名，对返回map无效
  configuration:
    map-underscore-to-camel-case: true