// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C10004Msg.proto

package com.enuos.live.proto.c10004msg;

public final class C10004 {
  private C10004() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C100040s2cOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 userId = 1;
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    long getUserId();

    // required string nickName = 2;
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    boolean hasNickName();
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    java.lang.String getNickName();
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    // required string thumbIconURL = 3;
    /**
     * <code>required string thumbIconURL = 3;</code>
     *
     * <pre>
     *头像
     * </pre>
     */
    boolean hasThumbIconURL();
    /**
     * <code>required string thumbIconURL = 3;</code>
     *
     * <pre>
     *头像
     * </pre>
     */
    java.lang.String getThumbIconURL();
    /**
     * <code>required string thumbIconURL = 3;</code>
     *
     * <pre>
     *头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getThumbIconURLBytes();

    // required int64 vip = 4;
    /**
     * <code>required int64 vip = 4;</code>
     *
     * <pre>
     *vip等级
     * </pre>
     */
    boolean hasVip();
    /**
     * <code>required int64 vip = 4;</code>
     *
     * <pre>
     *vip等级
     * </pre>
     */
    long getVip();
  }
  /**
   * Protobuf type {@code Platform.ModelC10004.C100040s2c}
   *
   * <pre>
   *会员等级公告
   * </pre>
   */
  public static final class C100040s2c extends
      com.google.protobuf.GeneratedMessage
      implements C100040s2cOrBuilder {
    // Use C100040s2c.newBuilder() to construct.
    private C100040s2c(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100040s2c(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100040s2c defaultInstance;
    public static C100040s2c getDefaultInstance() {
      return defaultInstance;
    }

    public C100040s2c getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100040s2c(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nickName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              thumbIconURL_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              vip_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100040s2c_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100040s2c_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.c10004msg.C10004.C100040s2c.class, com.enuos.live.proto.c10004msg.C10004.C100040s2c.Builder.class);
    }

    public static com.google.protobuf.Parser<C100040s2c> PARSER =
        new com.google.protobuf.AbstractParser<C100040s2c>() {
      public C100040s2c parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100040s2c(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100040s2c> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 userId = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public long getUserId() {
      return userId_;
    }

    // required string nickName = 2;
    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object nickName_;
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string thumbIconURL = 3;
    public static final int THUMBICONURL_FIELD_NUMBER = 3;
    private java.lang.Object thumbIconURL_;
    /**
     * <code>required string thumbIconURL = 3;</code>
     *
     * <pre>
     *头像
     * </pre>
     */
    public boolean hasThumbIconURL() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string thumbIconURL = 3;</code>
     *
     * <pre>
     *头像
     * </pre>
     */
    public java.lang.String getThumbIconURL() {
      java.lang.Object ref = thumbIconURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          thumbIconURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string thumbIconURL = 3;</code>
     *
     * <pre>
     *头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getThumbIconURLBytes() {
      java.lang.Object ref = thumbIconURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thumbIconURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 vip = 4;
    public static final int VIP_FIELD_NUMBER = 4;
    private long vip_;
    /**
     * <code>required int64 vip = 4;</code>
     *
     * <pre>
     *vip等级
     * </pre>
     */
    public boolean hasVip() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 vip = 4;</code>
     *
     * <pre>
     *vip等级
     * </pre>
     */
    public long getVip() {
      return vip_;
    }

    private void initFields() {
      userId_ = 0L;
      nickName_ = "";
      thumbIconURL_ = "";
      vip_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThumbIconURL()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getThumbIconURLBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, vip_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getThumbIconURLBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, vip_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100040s2c parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.c10004msg.C10004.C100040s2c prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10004.C100040s2c}
     *
     * <pre>
     *会员等级公告
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.c10004msg.C10004.C100040s2cOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100040s2c_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100040s2c_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.c10004msg.C10004.C100040s2c.class, com.enuos.live.proto.c10004msg.C10004.C100040s2c.Builder.class);
      }

      // Construct using com.enuos.live.proto.c10004msg.C10004.C100040s2c.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        thumbIconURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        vip_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100040s2c_descriptor;
      }

      public com.enuos.live.proto.c10004msg.C10004.C100040s2c getDefaultInstanceForType() {
        return com.enuos.live.proto.c10004msg.C10004.C100040s2c.getDefaultInstance();
      }

      public com.enuos.live.proto.c10004msg.C10004.C100040s2c build() {
        com.enuos.live.proto.c10004msg.C10004.C100040s2c result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.c10004msg.C10004.C100040s2c buildPartial() {
        com.enuos.live.proto.c10004msg.C10004.C100040s2c result = new com.enuos.live.proto.c10004msg.C10004.C100040s2c(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.thumbIconURL_ = thumbIconURL_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.vip_ = vip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.c10004msg.C10004.C100040s2c) {
          return mergeFrom((com.enuos.live.proto.c10004msg.C10004.C100040s2c)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.c10004msg.C10004.C100040s2c other) {
        if (other == com.enuos.live.proto.c10004msg.C10004.C100040s2c.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasNickName()) {
          bitField0_ |= 0x00000002;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasThumbIconURL()) {
          bitField0_ |= 0x00000004;
          thumbIconURL_ = other.thumbIconURL_;
          onChanged();
        }
        if (other.hasVip()) {
          setVip(other.getVip());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasNickName()) {
          
          return false;
        }
        if (!hasThumbIconURL()) {
          
          return false;
        }
        if (!hasVip()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.c10004msg.C10004.C100040s2c parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.c10004msg.C10004.C100040s2c) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 userId = 1;
      private long userId_ ;
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required string nickName = 2;
      private java.lang.Object nickName_ = "";
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *昵称
       * </pre>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }

      // required string thumbIconURL = 3;
      private java.lang.Object thumbIconURL_ = "";
      /**
       * <code>required string thumbIconURL = 3;</code>
       *
       * <pre>
       *头像
       * </pre>
       */
      public boolean hasThumbIconURL() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string thumbIconURL = 3;</code>
       *
       * <pre>
       *头像
       * </pre>
       */
      public java.lang.String getThumbIconURL() {
        java.lang.Object ref = thumbIconURL_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          thumbIconURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string thumbIconURL = 3;</code>
       *
       * <pre>
       *头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getThumbIconURLBytes() {
        java.lang.Object ref = thumbIconURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thumbIconURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string thumbIconURL = 3;</code>
       *
       * <pre>
       *头像
       * </pre>
       */
      public Builder setThumbIconURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        thumbIconURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string thumbIconURL = 3;</code>
       *
       * <pre>
       *头像
       * </pre>
       */
      public Builder clearThumbIconURL() {
        bitField0_ = (bitField0_ & ~0x00000004);
        thumbIconURL_ = getDefaultInstance().getThumbIconURL();
        onChanged();
        return this;
      }
      /**
       * <code>required string thumbIconURL = 3;</code>
       *
       * <pre>
       *头像
       * </pre>
       */
      public Builder setThumbIconURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        thumbIconURL_ = value;
        onChanged();
        return this;
      }

      // required int64 vip = 4;
      private long vip_ ;
      /**
       * <code>required int64 vip = 4;</code>
       *
       * <pre>
       *vip等级
       * </pre>
       */
      public boolean hasVip() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 vip = 4;</code>
       *
       * <pre>
       *vip等级
       * </pre>
       */
      public long getVip() {
        return vip_;
      }
      /**
       * <code>required int64 vip = 4;</code>
       *
       * <pre>
       *vip等级
       * </pre>
       */
      public Builder setVip(long value) {
        bitField0_ |= 0x00000008;
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 vip = 4;</code>
       *
       * <pre>
       *vip等级
       * </pre>
       */
      public Builder clearVip() {
        bitField0_ = (bitField0_ & ~0x00000008);
        vip_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10004.C100040s2c)
    }

    static {
      defaultInstance = new C100040s2c(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10004.C100040s2c)
  }

  public interface C100041s2cOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 roomId = 1;
    /**
     * <code>required int64 roomId = 1;</code>
     *
     * <pre>
     *房间号
     * </pre>
     */
    boolean hasRoomId();
    /**
     * <code>required int64 roomId = 1;</code>
     *
     * <pre>
     *房间号
     * </pre>
     */
    long getRoomId();

    // required int64 fromUserId = 2;
    /**
     * <code>required int64 fromUserId = 2;</code>
     *
     * <pre>
     *送礼人ID
     * </pre>
     */
    boolean hasFromUserId();
    /**
     * <code>required int64 fromUserId = 2;</code>
     *
     * <pre>
     *送礼人ID
     * </pre>
     */
    long getFromUserId();

    // required string fromIconURL = 3;
    /**
     * <code>required string fromIconURL = 3;</code>
     *
     * <pre>
     *送礼人头像
     * </pre>
     */
    boolean hasFromIconURL();
    /**
     * <code>required string fromIconURL = 3;</code>
     *
     * <pre>
     *送礼人头像
     * </pre>
     */
    java.lang.String getFromIconURL();
    /**
     * <code>required string fromIconURL = 3;</code>
     *
     * <pre>
     *送礼人头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromIconURLBytes();

    // required string fromNickName = 4;
    /**
     * <code>required string fromNickName = 4;</code>
     *
     * <pre>
     *送礼人昵称
     * </pre>
     */
    boolean hasFromNickName();
    /**
     * <code>required string fromNickName = 4;</code>
     *
     * <pre>
     *送礼人昵称
     * </pre>
     */
    java.lang.String getFromNickName();
    /**
     * <code>required string fromNickName = 4;</code>
     *
     * <pre>
     *送礼人昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromNickNameBytes();

    // required int64 toUserId = 5;
    /**
     * <code>required int64 toUserId = 5;</code>
     *
     * <pre>
     *收礼人ID
     * </pre>
     */
    boolean hasToUserId();
    /**
     * <code>required int64 toUserId = 5;</code>
     *
     * <pre>
     *收礼人ID
     * </pre>
     */
    long getToUserId();

    // required string toIconURL = 6;
    /**
     * <code>required string toIconURL = 6;</code>
     *
     * <pre>
     *收礼人头像
     * </pre>
     */
    boolean hasToIconURL();
    /**
     * <code>required string toIconURL = 6;</code>
     *
     * <pre>
     *收礼人头像
     * </pre>
     */
    java.lang.String getToIconURL();
    /**
     * <code>required string toIconURL = 6;</code>
     *
     * <pre>
     *收礼人头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getToIconURLBytes();

    // required string toNickName = 7;
    /**
     * <code>required string toNickName = 7;</code>
     *
     * <pre>
     *收礼人昵称
     * </pre>
     */
    boolean hasToNickName();
    /**
     * <code>required string toNickName = 7;</code>
     *
     * <pre>
     *收礼人昵称
     * </pre>
     */
    java.lang.String getToNickName();
    /**
     * <code>required string toNickName = 7;</code>
     *
     * <pre>
     *收礼人昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getToNickNameBytes();

    // required string giftURL = 8;
    /**
     * <code>required string giftURL = 8;</code>
     *
     * <pre>
     *礼物图片
     * </pre>
     */
    boolean hasGiftURL();
    /**
     * <code>required string giftURL = 8;</code>
     *
     * <pre>
     *礼物图片
     * </pre>
     */
    java.lang.String getGiftURL();
    /**
     * <code>required string giftURL = 8;</code>
     *
     * <pre>
     *礼物图片
     * </pre>
     */
    com.google.protobuf.ByteString
        getGiftURLBytes();

    // required string giftName = 9;
    /**
     * <code>required string giftName = 9;</code>
     *
     * <pre>
     *礼物名称
     * </pre>
     */
    boolean hasGiftName();
    /**
     * <code>required string giftName = 9;</code>
     *
     * <pre>
     *礼物名称
     * </pre>
     */
    java.lang.String getGiftName();
    /**
     * <code>required string giftName = 9;</code>
     *
     * <pre>
     *礼物名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getGiftNameBytes();

    // required int64 giftNum = 10;
    /**
     * <code>required int64 giftNum = 10;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    boolean hasGiftNum();
    /**
     * <code>required int64 giftNum = 10;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    long getGiftNum();
  }
  /**
   * Protobuf type {@code Platform.ModelC10004.C100041s2c}
   *
   * <pre>
   *送礼公告
   * </pre>
   */
  public static final class C100041s2c extends
      com.google.protobuf.GeneratedMessage
      implements C100041s2cOrBuilder {
    // Use C100041s2c.newBuilder() to construct.
    private C100041s2c(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100041s2c(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100041s2c defaultInstance;
    public static C100041s2c getDefaultInstance() {
      return defaultInstance;
    }

    public C100041s2c getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100041s2c(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromUserId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fromIconURL_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fromNickName_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              toUserId_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              toIconURL_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              toNickName_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              giftURL_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              giftName_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              giftNum_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100041s2c_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100041s2c_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.enuos.live.proto.c10004msg.C10004.C100041s2c.class, com.enuos.live.proto.c10004msg.C10004.C100041s2c.Builder.class);
    }

    public static com.google.protobuf.Parser<C100041s2c> PARSER =
        new com.google.protobuf.AbstractParser<C100041s2c>() {
      public C100041s2c parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100041s2c(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100041s2c> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 roomId = 1;
    public static final int ROOMID_FIELD_NUMBER = 1;
    private long roomId_;
    /**
     * <code>required int64 roomId = 1;</code>
     *
     * <pre>
     *房间号
     * </pre>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 roomId = 1;</code>
     *
     * <pre>
     *房间号
     * </pre>
     */
    public long getRoomId() {
      return roomId_;
    }

    // required int64 fromUserId = 2;
    public static final int FROMUSERID_FIELD_NUMBER = 2;
    private long fromUserId_;
    /**
     * <code>required int64 fromUserId = 2;</code>
     *
     * <pre>
     *送礼人ID
     * </pre>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 fromUserId = 2;</code>
     *
     * <pre>
     *送礼人ID
     * </pre>
     */
    public long getFromUserId() {
      return fromUserId_;
    }

    // required string fromIconURL = 3;
    public static final int FROMICONURL_FIELD_NUMBER = 3;
    private java.lang.Object fromIconURL_;
    /**
     * <code>required string fromIconURL = 3;</code>
     *
     * <pre>
     *送礼人头像
     * </pre>
     */
    public boolean hasFromIconURL() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string fromIconURL = 3;</code>
     *
     * <pre>
     *送礼人头像
     * </pre>
     */
    public java.lang.String getFromIconURL() {
      java.lang.Object ref = fromIconURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromIconURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromIconURL = 3;</code>
     *
     * <pre>
     *送礼人头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromIconURLBytes() {
      java.lang.Object ref = fromIconURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromIconURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string fromNickName = 4;
    public static final int FROMNICKNAME_FIELD_NUMBER = 4;
    private java.lang.Object fromNickName_;
    /**
     * <code>required string fromNickName = 4;</code>
     *
     * <pre>
     *送礼人昵称
     * </pre>
     */
    public boolean hasFromNickName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string fromNickName = 4;</code>
     *
     * <pre>
     *送礼人昵称
     * </pre>
     */
    public java.lang.String getFromNickName() {
      java.lang.Object ref = fromNickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromNickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromNickName = 4;</code>
     *
     * <pre>
     *送礼人昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromNickNameBytes() {
      java.lang.Object ref = fromNickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromNickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 toUserId = 5;
    public static final int TOUSERID_FIELD_NUMBER = 5;
    private long toUserId_;
    /**
     * <code>required int64 toUserId = 5;</code>
     *
     * <pre>
     *收礼人ID
     * </pre>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 toUserId = 5;</code>
     *
     * <pre>
     *收礼人ID
     * </pre>
     */
    public long getToUserId() {
      return toUserId_;
    }

    // required string toIconURL = 6;
    public static final int TOICONURL_FIELD_NUMBER = 6;
    private java.lang.Object toIconURL_;
    /**
     * <code>required string toIconURL = 6;</code>
     *
     * <pre>
     *收礼人头像
     * </pre>
     */
    public boolean hasToIconURL() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string toIconURL = 6;</code>
     *
     * <pre>
     *收礼人头像
     * </pre>
     */
    public java.lang.String getToIconURL() {
      java.lang.Object ref = toIconURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toIconURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string toIconURL = 6;</code>
     *
     * <pre>
     *收礼人头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToIconURLBytes() {
      java.lang.Object ref = toIconURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toIconURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string toNickName = 7;
    public static final int TONICKNAME_FIELD_NUMBER = 7;
    private java.lang.Object toNickName_;
    /**
     * <code>required string toNickName = 7;</code>
     *
     * <pre>
     *收礼人昵称
     * </pre>
     */
    public boolean hasToNickName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string toNickName = 7;</code>
     *
     * <pre>
     *收礼人昵称
     * </pre>
     */
    public java.lang.String getToNickName() {
      java.lang.Object ref = toNickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toNickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string toNickName = 7;</code>
     *
     * <pre>
     *收礼人昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToNickNameBytes() {
      java.lang.Object ref = toNickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toNickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string giftURL = 8;
    public static final int GIFTURL_FIELD_NUMBER = 8;
    private java.lang.Object giftURL_;
    /**
     * <code>required string giftURL = 8;</code>
     *
     * <pre>
     *礼物图片
     * </pre>
     */
    public boolean hasGiftURL() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string giftURL = 8;</code>
     *
     * <pre>
     *礼物图片
     * </pre>
     */
    public java.lang.String getGiftURL() {
      java.lang.Object ref = giftURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          giftURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string giftURL = 8;</code>
     *
     * <pre>
     *礼物图片
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGiftURLBytes() {
      java.lang.Object ref = giftURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        giftURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string giftName = 9;
    public static final int GIFTNAME_FIELD_NUMBER = 9;
    private java.lang.Object giftName_;
    /**
     * <code>required string giftName = 9;</code>
     *
     * <pre>
     *礼物名称
     * </pre>
     */
    public boolean hasGiftName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string giftName = 9;</code>
     *
     * <pre>
     *礼物名称
     * </pre>
     */
    public java.lang.String getGiftName() {
      java.lang.Object ref = giftName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          giftName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string giftName = 9;</code>
     *
     * <pre>
     *礼物名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGiftNameBytes() {
      java.lang.Object ref = giftName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        giftName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 giftNum = 10;
    public static final int GIFTNUM_FIELD_NUMBER = 10;
    private long giftNum_;
    /**
     * <code>required int64 giftNum = 10;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    public boolean hasGiftNum() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int64 giftNum = 10;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    public long getGiftNum() {
      return giftNum_;
    }

    private void initFields() {
      roomId_ = 0L;
      fromUserId_ = 0L;
      fromIconURL_ = "";
      fromNickName_ = "";
      toUserId_ = 0L;
      toIconURL_ = "";
      toNickName_ = "";
      giftURL_ = "";
      giftName_ = "";
      giftNum_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromIconURL()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToIconURL()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGiftURL()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGiftName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGiftNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, roomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fromUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromIconURLBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFromNickNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, toUserId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getToIconURLBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getToNickNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getGiftURLBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getGiftNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, giftNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, roomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fromUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromIconURLBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFromNickNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, toUserId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getToIconURLBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getToNickNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getGiftURLBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getGiftNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, giftNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.enuos.live.proto.c10004msg.C10004.C100041s2c parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enuos.live.proto.c10004msg.C10004.C100041s2c prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10004.C100041s2c}
     *
     * <pre>
     *送礼公告
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enuos.live.proto.c10004msg.C10004.C100041s2cOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100041s2c_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100041s2c_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.enuos.live.proto.c10004msg.C10004.C100041s2c.class, com.enuos.live.proto.c10004msg.C10004.C100041s2c.Builder.class);
      }

      // Construct using com.enuos.live.proto.c10004msg.C10004.C100041s2c.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromIconURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fromNickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        toUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        toIconURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        toNickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        giftURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        giftName_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        giftNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enuos.live.proto.c10004msg.C10004.internal_static_Platform_ModelC10004_C100041s2c_descriptor;
      }

      public com.enuos.live.proto.c10004msg.C10004.C100041s2c getDefaultInstanceForType() {
        return com.enuos.live.proto.c10004msg.C10004.C100041s2c.getDefaultInstance();
      }

      public com.enuos.live.proto.c10004msg.C10004.C100041s2c build() {
        com.enuos.live.proto.c10004msg.C10004.C100041s2c result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.enuos.live.proto.c10004msg.C10004.C100041s2c buildPartial() {
        com.enuos.live.proto.c10004msg.C10004.C100041s2c result = new com.enuos.live.proto.c10004msg.C10004.C100041s2c(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomId_ = roomId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromIconURL_ = fromIconURL_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromNickName_ = fromNickName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toIconURL_ = toIconURL_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.toNickName_ = toNickName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.giftURL_ = giftURL_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.giftName_ = giftName_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.giftNum_ = giftNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enuos.live.proto.c10004msg.C10004.C100041s2c) {
          return mergeFrom((com.enuos.live.proto.c10004msg.C10004.C100041s2c)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.enuos.live.proto.c10004msg.C10004.C100041s2c other) {
        if (other == com.enuos.live.proto.c10004msg.C10004.C100041s2c.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasFromIconURL()) {
          bitField0_ |= 0x00000004;
          fromIconURL_ = other.fromIconURL_;
          onChanged();
        }
        if (other.hasFromNickName()) {
          bitField0_ |= 0x00000008;
          fromNickName_ = other.fromNickName_;
          onChanged();
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasToIconURL()) {
          bitField0_ |= 0x00000020;
          toIconURL_ = other.toIconURL_;
          onChanged();
        }
        if (other.hasToNickName()) {
          bitField0_ |= 0x00000040;
          toNickName_ = other.toNickName_;
          onChanged();
        }
        if (other.hasGiftURL()) {
          bitField0_ |= 0x00000080;
          giftURL_ = other.giftURL_;
          onChanged();
        }
        if (other.hasGiftName()) {
          bitField0_ |= 0x00000100;
          giftName_ = other.giftName_;
          onChanged();
        }
        if (other.hasGiftNum()) {
          setGiftNum(other.getGiftNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoomId()) {
          
          return false;
        }
        if (!hasFromUserId()) {
          
          return false;
        }
        if (!hasFromIconURL()) {
          
          return false;
        }
        if (!hasFromNickName()) {
          
          return false;
        }
        if (!hasToUserId()) {
          
          return false;
        }
        if (!hasToIconURL()) {
          
          return false;
        }
        if (!hasToNickName()) {
          
          return false;
        }
        if (!hasGiftURL()) {
          
          return false;
        }
        if (!hasGiftName()) {
          
          return false;
        }
        if (!hasGiftNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.enuos.live.proto.c10004msg.C10004.C100041s2c parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.enuos.live.proto.c10004msg.C10004.C100041s2c) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 roomId = 1;
      private long roomId_ ;
      /**
       * <code>required int64 roomId = 1;</code>
       *
       * <pre>
       *房间号
       * </pre>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 roomId = 1;</code>
       *
       * <pre>
       *房间号
       * </pre>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int64 roomId = 1;</code>
       *
       * <pre>
       *房间号
       * </pre>
       */
      public Builder setRoomId(long value) {
        bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roomId = 1;</code>
       *
       * <pre>
       *房间号
       * </pre>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 fromUserId = 2;
      private long fromUserId_ ;
      /**
       * <code>required int64 fromUserId = 2;</code>
       *
       * <pre>
       *送礼人ID
       * </pre>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 fromUserId = 2;</code>
       *
       * <pre>
       *送礼人ID
       * </pre>
       */
      public long getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>required int64 fromUserId = 2;</code>
       *
       * <pre>
       *送礼人ID
       * </pre>
       */
      public Builder setFromUserId(long value) {
        bitField0_ |= 0x00000002;
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fromUserId = 2;</code>
       *
       * <pre>
       *送礼人ID
       * </pre>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromUserId_ = 0L;
        onChanged();
        return this;
      }

      // required string fromIconURL = 3;
      private java.lang.Object fromIconURL_ = "";
      /**
       * <code>required string fromIconURL = 3;</code>
       *
       * <pre>
       *送礼人头像
       * </pre>
       */
      public boolean hasFromIconURL() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string fromIconURL = 3;</code>
       *
       * <pre>
       *送礼人头像
       * </pre>
       */
      public java.lang.String getFromIconURL() {
        java.lang.Object ref = fromIconURL_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromIconURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromIconURL = 3;</code>
       *
       * <pre>
       *送礼人头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromIconURLBytes() {
        java.lang.Object ref = fromIconURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromIconURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromIconURL = 3;</code>
       *
       * <pre>
       *送礼人头像
       * </pre>
       */
      public Builder setFromIconURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromIconURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromIconURL = 3;</code>
       *
       * <pre>
       *送礼人头像
       * </pre>
       */
      public Builder clearFromIconURL() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromIconURL_ = getDefaultInstance().getFromIconURL();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromIconURL = 3;</code>
       *
       * <pre>
       *送礼人头像
       * </pre>
       */
      public Builder setFromIconURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fromIconURL_ = value;
        onChanged();
        return this;
      }

      // required string fromNickName = 4;
      private java.lang.Object fromNickName_ = "";
      /**
       * <code>required string fromNickName = 4;</code>
       *
       * <pre>
       *送礼人昵称
       * </pre>
       */
      public boolean hasFromNickName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string fromNickName = 4;</code>
       *
       * <pre>
       *送礼人昵称
       * </pre>
       */
      public java.lang.String getFromNickName() {
        java.lang.Object ref = fromNickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromNickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromNickName = 4;</code>
       *
       * <pre>
       *送礼人昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromNickNameBytes() {
        java.lang.Object ref = fromNickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromNickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromNickName = 4;</code>
       *
       * <pre>
       *送礼人昵称
       * </pre>
       */
      public Builder setFromNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromNickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromNickName = 4;</code>
       *
       * <pre>
       *送礼人昵称
       * </pre>
       */
      public Builder clearFromNickName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromNickName_ = getDefaultInstance().getFromNickName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromNickName = 4;</code>
       *
       * <pre>
       *送礼人昵称
       * </pre>
       */
      public Builder setFromNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromNickName_ = value;
        onChanged();
        return this;
      }

      // required int64 toUserId = 5;
      private long toUserId_ ;
      /**
       * <code>required int64 toUserId = 5;</code>
       *
       * <pre>
       *收礼人ID
       * </pre>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 toUserId = 5;</code>
       *
       * <pre>
       *收礼人ID
       * </pre>
       */
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <code>required int64 toUserId = 5;</code>
       *
       * <pre>
       *收礼人ID
       * </pre>
       */
      public Builder setToUserId(long value) {
        bitField0_ |= 0x00000010;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 toUserId = 5;</code>
       *
       * <pre>
       *收礼人ID
       * </pre>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      // required string toIconURL = 6;
      private java.lang.Object toIconURL_ = "";
      /**
       * <code>required string toIconURL = 6;</code>
       *
       * <pre>
       *收礼人头像
       * </pre>
       */
      public boolean hasToIconURL() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string toIconURL = 6;</code>
       *
       * <pre>
       *收礼人头像
       * </pre>
       */
      public java.lang.String getToIconURL() {
        java.lang.Object ref = toIconURL_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toIconURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string toIconURL = 6;</code>
       *
       * <pre>
       *收礼人头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToIconURLBytes() {
        java.lang.Object ref = toIconURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toIconURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string toIconURL = 6;</code>
       *
       * <pre>
       *收礼人头像
       * </pre>
       */
      public Builder setToIconURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        toIconURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string toIconURL = 6;</code>
       *
       * <pre>
       *收礼人头像
       * </pre>
       */
      public Builder clearToIconURL() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toIconURL_ = getDefaultInstance().getToIconURL();
        onChanged();
        return this;
      }
      /**
       * <code>required string toIconURL = 6;</code>
       *
       * <pre>
       *收礼人头像
       * </pre>
       */
      public Builder setToIconURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        toIconURL_ = value;
        onChanged();
        return this;
      }

      // required string toNickName = 7;
      private java.lang.Object toNickName_ = "";
      /**
       * <code>required string toNickName = 7;</code>
       *
       * <pre>
       *收礼人昵称
       * </pre>
       */
      public boolean hasToNickName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string toNickName = 7;</code>
       *
       * <pre>
       *收礼人昵称
       * </pre>
       */
      public java.lang.String getToNickName() {
        java.lang.Object ref = toNickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toNickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string toNickName = 7;</code>
       *
       * <pre>
       *收礼人昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToNickNameBytes() {
        java.lang.Object ref = toNickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toNickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string toNickName = 7;</code>
       *
       * <pre>
       *收礼人昵称
       * </pre>
       */
      public Builder setToNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        toNickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string toNickName = 7;</code>
       *
       * <pre>
       *收礼人昵称
       * </pre>
       */
      public Builder clearToNickName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        toNickName_ = getDefaultInstance().getToNickName();
        onChanged();
        return this;
      }
      /**
       * <code>required string toNickName = 7;</code>
       *
       * <pre>
       *收礼人昵称
       * </pre>
       */
      public Builder setToNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        toNickName_ = value;
        onChanged();
        return this;
      }

      // required string giftURL = 8;
      private java.lang.Object giftURL_ = "";
      /**
       * <code>required string giftURL = 8;</code>
       *
       * <pre>
       *礼物图片
       * </pre>
       */
      public boolean hasGiftURL() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string giftURL = 8;</code>
       *
       * <pre>
       *礼物图片
       * </pre>
       */
      public java.lang.String getGiftURL() {
        java.lang.Object ref = giftURL_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          giftURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string giftURL = 8;</code>
       *
       * <pre>
       *礼物图片
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGiftURLBytes() {
        java.lang.Object ref = giftURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          giftURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string giftURL = 8;</code>
       *
       * <pre>
       *礼物图片
       * </pre>
       */
      public Builder setGiftURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        giftURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string giftURL = 8;</code>
       *
       * <pre>
       *礼物图片
       * </pre>
       */
      public Builder clearGiftURL() {
        bitField0_ = (bitField0_ & ~0x00000080);
        giftURL_ = getDefaultInstance().getGiftURL();
        onChanged();
        return this;
      }
      /**
       * <code>required string giftURL = 8;</code>
       *
       * <pre>
       *礼物图片
       * </pre>
       */
      public Builder setGiftURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        giftURL_ = value;
        onChanged();
        return this;
      }

      // required string giftName = 9;
      private java.lang.Object giftName_ = "";
      /**
       * <code>required string giftName = 9;</code>
       *
       * <pre>
       *礼物名称
       * </pre>
       */
      public boolean hasGiftName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string giftName = 9;</code>
       *
       * <pre>
       *礼物名称
       * </pre>
       */
      public java.lang.String getGiftName() {
        java.lang.Object ref = giftName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          giftName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string giftName = 9;</code>
       *
       * <pre>
       *礼物名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGiftNameBytes() {
        java.lang.Object ref = giftName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          giftName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string giftName = 9;</code>
       *
       * <pre>
       *礼物名称
       * </pre>
       */
      public Builder setGiftName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        giftName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string giftName = 9;</code>
       *
       * <pre>
       *礼物名称
       * </pre>
       */
      public Builder clearGiftName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        giftName_ = getDefaultInstance().getGiftName();
        onChanged();
        return this;
      }
      /**
       * <code>required string giftName = 9;</code>
       *
       * <pre>
       *礼物名称
       * </pre>
       */
      public Builder setGiftNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        giftName_ = value;
        onChanged();
        return this;
      }

      // required int64 giftNum = 10;
      private long giftNum_ ;
      /**
       * <code>required int64 giftNum = 10;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public boolean hasGiftNum() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int64 giftNum = 10;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public long getGiftNum() {
        return giftNum_;
      }
      /**
       * <code>required int64 giftNum = 10;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public Builder setGiftNum(long value) {
        bitField0_ |= 0x00000200;
        giftNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 giftNum = 10;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public Builder clearGiftNum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        giftNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10004.C100041s2c)
    }

    static {
      defaultInstance = new C100041s2c(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10004.C100041s2c)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10004_C100040s2c_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10004_C100040s2c_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10004_C100041s2c_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10004_C100041s2c_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017C10004Msg.proto\022\024Platform.ModelC10004\"" +
      "Q\n\nC100040s2c\022\016\n\006userId\030\001 \002(\003\022\020\n\010nickNam" +
      "e\030\002 \002(\t\022\024\n\014thumbIconURL\030\003 \002(\t\022\013\n\003vip\030\004 \002" +
      "(\003\"\310\001\n\nC100041s2c\022\016\n\006roomId\030\001 \002(\003\022\022\n\nfro" +
      "mUserId\030\002 \002(\003\022\023\n\013fromIconURL\030\003 \002(\t\022\024\n\014fr" +
      "omNickName\030\004 \002(\t\022\020\n\010toUserId\030\005 \002(\003\022\021\n\tto" +
      "IconURL\030\006 \002(\t\022\022\n\ntoNickName\030\007 \002(\t\022\017\n\007gif" +
      "tURL\030\010 \002(\t\022\020\n\010giftName\030\t \002(\t\022\017\n\007giftNum\030" +
      "\n \002(\003B(\n\036com.enuos.live.proto.c10004msgB" +
      "\006C10004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_ModelC10004_C100040s2c_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_ModelC10004_C100040s2c_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10004_C100040s2c_descriptor,
              new java.lang.String[] { "UserId", "NickName", "ThumbIconURL", "Vip", });
          internal_static_Platform_ModelC10004_C100041s2c_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_ModelC10004_C100041s2c_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10004_C100041s2c_descriptor,
              new java.lang.String[] { "RoomId", "FromUserId", "FromIconURL", "FromNickName", "ToUserId", "ToIconURL", "ToNickName", "GiftURL", "GiftName", "GiftNum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
